_wandb:
    value:
        cli_version: 0.21.3
        e:
            ia2tsvk1ci1iiz7w3qbnmtgpugd7ld4y:
                args:
                    - clean_sample.csv:latest
                    - "0.2"
                    - --random_seed
                    - "42"
                    - --stratify_by
                    - neighbourhood_group
                codePath: components/train_val_test_split/run.py
                codePathLocal: run.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1081101176832"
                        used: "26870419456"
                email: a.barrio@iberdrola.es
                executable: /home/u339700/miniconda3/envs/mlflow-9e90f5fe2c8b525335212978234fa75adebb4614/bin/python
                git:
                    commit: 3b9025f87252a5a74917e37851ca9bee24f1848f
                    remote: https://github.com/U339700_ibe/build-ml-pipeline-for-short-term-rental-prices.git
                host: HOR8GZGKR3
                memory:
                    total: "8005054464"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /mnt/c/Users/u339700/Desktop/build-ml-pipeline-for-short-term-rental-prices/components/train_val_test_split/run.py
                python: CPython 3.13.12
                root: /mnt/c/Users/u339700/Desktop/build-ml-pipeline-for-short-term-rental-prices/components/train_val_test_split
                startedAt: "2026-02-16T12:16:56.780923Z"
                writerId: ia2tsvk1ci1iiz7w3qbnmtgpugd7ld4y
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "4": 3.13.12
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
input:
    value: clean_sample.csv:latest
random_seed:
    value: 42
stratify_by:
    value: neighbourhood_group
test_size:
    value: 0.2
