_wandb:
    value:
        cli_version: 0.21.3
        e:
            yfekbo4cm0aqfn6bwctbsoiver6yytw7:
                args:
                    - --trainval_artifact
                    - trainval_data.csv:latest
                    - --val_size
                    - "0.2"
                    - --random_seed
                    - "42"
                    - --stratify_by
                    - neighbourhood_group
                    - --rf_config
                    - /mnt/c/Users/u339700/Desktop/build-ml-pipeline-for-short-term-rental-prices/rf_config.json
                    - --max_tfidf_features
                    - "10"
                    - --output_artifact
                    - random_forest_export
                codePath: src/train_random_forest/run.py
                codePathLocal: run.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1081101176832"
                        used: "27486801920"
                email: a.barrio@iberdrola.es
                executable: /home/u339700/miniconda3/envs/mlflow-114dfdd7a6f8d813e5c5a71f8972961923f526b5/bin/python
                git:
                    commit: 3b9025f87252a5a74917e37851ca9bee24f1848f
                    remote: https://github.com/U339700_ibe/build-ml-pipeline-for-short-term-rental-prices.git
                host: HOR8GZGKR3
                memory:
                    total: "8005054464"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /mnt/c/Users/u339700/Desktop/build-ml-pipeline-for-short-term-rental-prices/src/train_random_forest/run.py
                python: CPython 3.13.12
                root: /mnt/c/Users/u339700/Desktop/build-ml-pipeline-for-short-term-rental-prices/src/train_random_forest
                startedAt: "2026-02-16T13:23:11.097037Z"
                writerId: yfekbo4cm0aqfn6bwctbsoiver6yytw7
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 62
            "4": 3.13.12
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
criterion:
    value: squared_error
max_depth:
    value: 15
max_features:
    value: 0.1
max_tfidf_features:
    value: 10
min_samples_leaf:
    value: 3
min_samples_split:
    value: 4
n_estimators:
    value: 100
n_jobs:
    value: -1
oob_score:
    value: true
output_artifact:
    value: random_forest_export
random_seed:
    value: 42
rf_config:
    value: /mnt/c/Users/u339700/Desktop/build-ml-pipeline-for-short-term-rental-prices/rf_config.json
stratify_by:
    value: neighbourhood_group
trainval_artifact:
    value: trainval_data.csv:latest
val_size:
    value: 0.2
